name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t azharali0564/ubuntu-image:latest .

    - name: Push Docker Image to DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u azharali0564 --password-stdin
        docker push azharali0564/ubuntu-image:latest
